"""listing seat_num

Revision ID: 8e2c66dcb6a9
Revises: efd7577a83d6
Create Date: 2025-09-08 21:40:30.015087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2c66dcb6a9'
down_revision: Union[str, Sequence[str], None] = 'efd7577a83d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('seat_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'seat_num')
    # ### end Alembic commands ###
