"""clean models + watchlists/notifications

Revision ID: 938132443f40
Revises: bca36651730a
Create Date: 2025-09-10 00:37:59.294100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938132443f40'
down_revision: Union[str, Sequence[str], None] = 'bca36651730a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artists_name_key'), 'artists', type_='unique')
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=True)
    op.create_index(op.f('ix_events_artist_id'), 'events', ['artist_id'], unique=False)
    op.create_index(op.f('ix_listings_event_id'), 'listings', ['event_id'], unique=False)
    op.create_index(op.f('ix_listings_section_id'), 'listings', ['section_id'], unique=False)
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_notifications_listing_id'), 'notifications', ['listing_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_unique_constraint('uq_notifications_user_listing', 'notifications', ['user_id', 'listing_id'])
    op.create_index(op.f('ix_sections_venue_id'), 'sections', ['venue_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('venues_name_key'), 'venues', type_='unique')
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=True)
    op.create_index(op.f('ix_watchlists_event_id'), 'watchlists', ['event_id'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_event_id'), table_name='watchlists')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.create_unique_constraint(op.f('venues_name_key'), 'venues', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_sections_venue_id'), table_name='sections')
    op.drop_constraint('uq_notifications_user_listing', 'notifications', type_='unique')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_listing_id'), table_name='notifications')
    op.drop_column('notifications', 'created_at')
    op.drop_index(op.f('ix_listings_section_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_event_id'), table_name='listings')
    op.drop_index(op.f('ix_events_artist_id'), table_name='events')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.create_unique_constraint(op.f('artists_name_key'), 'artists', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
